enum Choices {
    PLAYER,
    OPPONENT,
    CARD_IN_HAND,
    CARD_IN_DISCARD
}

enum AIPointer {
    SELF,
    OPPONENT_MOST_CARDS,
    OPPONENT_LEAST_CARDS,
    OPPONENT_RANDOM,
    PLAYER_RANDOM,
    PLAYER_MOST_CARDS,
    PLAYER_LEAST_CARDS,
    CARD_IN_HAND_LEAST_POWER,
    CARD_IN_HAND_MOST_POWER,
    CARD_IN_HAND_RANDOM,
    CARD_IN_DISCARD_LEAST_POWER,
    CARD_IN_DISCARD_MOST_POWER,
    CARD_IN_DISCARD_RANDOM,
    OPPONENT_MOST_TURNS_REMAINING,
    OPPONENT_LEAST_TURNS_REMAINING,
    PLAYER_MOST_TURNS_REMAINING,
    PLAYER_LEAST_TURNS_REMAINING
}

enum Rarity {
    BASIC,
    COMMON,
    UNCOMMON,
    RARE,
    MYTHIC,
    LEGENDARY,
    HAXOR
}

export { Choices, AIPointer, Rarity }